### ISSUE TITLE
Make use of delta in Unit test comparison

### ISSUE THREAD

**Issue by mjw99** [mlopz/ETK4J#12]
Comparing in this manner:
https://github.com/StaticBeagle/ETK4J/blob/05b561c86b48eb44b0cc04f020ea3dbf10b0f200/src/test/java/com/wildbitsfoundry/etk4j/signals/filters/AnalogFilterTest.java#L328
will not make use of the delta tolerance and may fail.

I think it is what is causing these fails: https://github.com/mjw99/ETK4J/runs/5869413085?check_suite_focus=true

**Comment by staticbeagle** [comment]
Thanks for reporting the issue. I don't see the issue on my side, but you bring a really good point. I'll look into it.

**Comment by mjw99** [comment]
I don't see it locally; I only see it in the Actions CI that I set up on my fork.

**Comment by staticbeagle** [comment]
I changed the failing unit tests to use `double` comparisons with delta instead of comparing the array of `Complex`. Hopefully that will take of the issue. Please let me know if everything looks good after the change.

**Comment by mjw99** [comment]
Many thanks; this has fixed the issue.
